name: John Doe
age: 30
occupation: Software Developer
database:
  host: localhost
  port: 5432
  user: admin
  password: secret
cities:
  - Chicago
  - Columbia
  - St Louis
models:
  - name: yolov11n-seg
    type: seg
    version: 1.2
  - name: yolov11n-pose
    type: pose
    version: 1.1
paths:
  input_dirs:
    - /data/raw
    - /data/clean
  output_dir: /data/output
training:
  epochs: 100
  batch_size: 16
  optimizer:
    type: Adam
    lr: 0.001
    weight_decay: 0.0001
description: |
  This is a long text.
  Line 2 will still be a new line.
  Line 3 keeps indentation.
summary: >
  This is a long sentence
  that will be folded into
  a single line after loading.
title: "Best Model: YOLOv11"
path: "C:\\Users\\TQ\\data\\images"